// <auto-generated />
using System;
using Igrannonica.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Igrannonica.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20220515003636_cetvrtamigracija")]
    partial class cetvrtamigracija
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Igrannonica.Models.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RandomFileName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("SessionID")
                        .HasColumnType("int");

                    b.Property<int?>("UserForeignKey")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RandomFileName")
                        .IsUnique();

                    b.HasIndex("SessionID")
                        .IsUnique();

                    b.HasIndex("UserForeignKey");

                    b.ToTable("File");
                });

            modelBuilder.Entity("Igrannonica.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("passwordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("tempPassword")
                        .HasColumnType("longtext");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("verifiedMail")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("verifyNumber")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("Igrannonica.Models.File", b =>
                {
                    b.HasOne("Igrannonica.Models.User", "User")
                        .WithMany("Files")
                        .HasForeignKey("UserForeignKey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Igrannonica.Models.User", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
